version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependincies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - echo Build complete...

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build