export const USER_CHECK_REQUEST = 'USER_CHECK_REQUEST';
export const USER_CHECK_SUCCESS = 'USER_CHECK_SUCCESS';
export const USER_CHECK_ERROR = 'USER_CHECK_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_BREADCRUMB_ITEMS = 'SET_BREADCRUMB_ITEMS';

export const DATA_FETCH_REQUEST = 'DATA_FETCH_REQUEST';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_ERROR = 'DATA_FETCH_ERROR';

export const SET_FILTERS = 'SET_FILTERS';

export const PRODUCT_ANALYSIS_DATA_FETCH_REQUEST = 'PRODUCT_ANALYSIS_DATA_FETCH_REQUEST';
export const PRODUCT_ANALYSIS_DATA_FETCH_SUCCESS = 'PRODUCT_ANALYSIS_DATA_FETCH_SUCCESS';
export const PRODUCT_ANALYSIS_DATA_FETCH_ERROR = 'PRODUCT_ANALYSIS_DATA_FETCH_ERROR';

export const OVERVIEW_DATA_FETCH_REQUEST = 'OVERVIEW_DATA_FETCH_REQUEST';
export const OVERVIEW_DATA_FETCH_SUCCESS = 'OVERVIEW_DATA_FETCH_SUCCESS';
export const OVERVIEW_DATA_FETCH_ERROR = 'OVERVIEW_DATA_FETCH_ERROR';

//Layout
export const TOGGLE = 'TOGGLE';
export const CHANGE_SIDEBAR_TYPE = 'CHANGE_SIDEBAR_TYPE';